# Generated by Django 4.2.7 on 2023-11-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_year',
            field=models.IntegerField(default=0),
        ),
    ]
