# Generated by Django 4.2.7 on 2023-11-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carmodel_car_price_alter_carmodel_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_year',
            field=models.IntegerField(),
        ),
    ]
