# Generated by Django 4.2.7 on 2023-11-11 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carmodel_car_price_alter_carmodel_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_brand',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[А-ЯЁІЇЄҐ][А-яёЁіІєЄїЇґҐ]{1,49}|[A-Z][a-zA-Z\\d]{1,49}$', 'First letter uppercase min 2 max 25 ch')]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_model',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
