# Generated by Django 4.2.7 on 2023-11-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_userpostsmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpostsmodel',
            name='car',
        ),
    ]
