# Generated by Django 4.2.7 on 2023-11-11 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_userpostsmodel_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpostsmodel',
            old_name='status',
            new_name='active_status',
        ),
        migrations.AlterField(
            model_name='userpostsmodel',
            name='city',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[А-ЯЁІЇЄҐ][А-яёЁіІєЄїЇґҐ]{1,49}$', ['only letters, without special characters', 'First letter uppercase', 'min 3 max 50 ch'])]),
        ),
        migrations.AlterField(
            model_name='userpostsmodel',
            name='region',
            field=models.CharField(choices=[('Вінницька', 'Vinnytsia'), ('Волинська', 'Volyn'), ('Дніпропетровська', 'Dnipropetrovsk'), ('Донецька', 'Donetsk'), ('Житомирська', 'Zhytomyr'), ('Закарпатська', 'Zakarpattia'), ('Запорізька', 'Zaporizhia'), ('Івано - Франківська', 'Ivano Frankivsk'), ('Київська', 'Kyiv'), ('Кіровоградська', 'Kirovohrad'), ('Луганська', 'Luhansk'), ('Львівська', 'Lviv'), ('Миколаївська', 'Mykolaiv'), ('Одеська', 'Odessa'), ('Полтавська', 'Poltava'), ('Рівненська', 'Rivne'), ('Сумська', 'Sumy'), ('Тернопільська', 'Ternopil'), ('Харківська', 'Kharkiv'), ('Херсонська', 'Kherson'), ('Хмельницька', 'Khmelnytskyi'), ('Черкаська', 'Cherkasy'), ('Чернівецька', 'Chernivtsi'), ('Чернігівська', 'Chernihiv')], max_length=30),
        ),
    ]
