# Generated by Django 4.2.7 on 2023-11-11 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilemodel_usermodel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='account_status',
            field=models.CharField(default='base', max_length=7),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[А-ЯЁІЇЄҐ][А-яёЁіІєЄїЇґҐ]{1,49}|[A-Z][a-zA-Z\\d]{1,49}$', ['only letters, without special characters', 'First letter uppercase', 'min 2 max 50 ch'])]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[А-ЯЁІЇЄҐ][А-яёЁіІєЄїЇґҐ]{1,49}|[A-Z][a-zA-Z\\d]{1,49}$', ['only letters, without special characters', 'First letter uppercase', 'min 2 max 50 ch'])]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=(?:.*[`~!@#$%^&*()\\-_+=\\\\\\|\\\'\\"\\;\\:\\/?.>,<\\[\\]\\{\\}]){2,})[a-zA-Z\\d`~!@#$%^&*()\\-_+=\\\\\\|\\\'\\"\\;\\:\\/?.>,<\\[\\]\\{\\}]{8,30}', ['min 1 lowercase ch', 'min 1 uppercase ch', 'min 1 digit', 'min 2 special character', 'length 8-30'])]),
        ),
    ]
